import { Inter } from "next/font/google";
import "./globals.css";
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Khatri Jewellers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Khatri Jewellers</title>
      </head>
      <body  className={inter.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
